title: GoRoMa
description: Quick and easy configuration options intended for administators of workspaces which utilise Google Workspace, MacOS, and Remotely Operate.
theme: just-the-docs

url: https://biosplus.github.io/GoRoMa/

aux_links:
  Template Repository: https://github.com/biosplus/GoRoMa
